### ISSUE TITLE
Chickens 2 Neoforge 1.20.4, Incubator automation doesn't work

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/Chickens#73] opened 2024-04-29 17:04 UTC
I'm not sure the design intent but the automation on this block is not working right. 
You can hopper eggs into and out of the block but they dont actually incubate, if you dont hopper out they're just completely inaccessible. So I assume either automation should be disabled and this is meant to be entirely manual or the automation is partially implemented.

**Comment by brandon3055** [comment] 2024-05-01 21:44
This is not intended, behaviour. I tracked this down to a bug in the PolyLib NeoForge inventory capability implementation.
This should be resolved with the next Polylib update.

The intended behaviour is for everything to work intuitively, Items will only go into slots that can accept them, and items can only be extracted when it makes sense for them to be extracted.

**Comment by furtabs** [comment] 2024-05-09 21:21
@brandon3055 can you release this fix for 1.20.1 on CF

**Comment by Saereth** [comment] 2024-05-15 15:06
tested and working here on neo

**Comment by gigabit101** [comment] 2024-05-16 09:51
make sure you are using the latest version of PolyLib for 1.20.1

**Closed as completed** 2024-05-16 09:52 UTC
Labels: bug, fix in dev
